<?php
/*
 * config/comprobantes.php
 * Tabla oficial de tipos de comprobante de ARCA (código => tipo, letra, descripción).
 * Fuente: tabla de códigos de comprobante de AFIP/ARCA.
 * 'tipo' se usa para la lógica del resumen (las Notas de Crédito restan).
 */
return [
    1 => ['tipo' => 'Factura', 'letra' => 'A', 'desc' => 'FACTURA A'],
    2 => ['tipo' => 'Nota de Débito', 'letra' => 'A', 'desc' => 'NOTA DE DEBITO A'],
    3 => ['tipo' => 'Nota de Crédito', 'letra' => 'A', 'desc' => 'NOTA DE CREDITO A'],
    4 => ['tipo' => 'Recibo', 'letra' => 'A', 'desc' => 'RECIBO A'],
    5 => ['tipo' => 'Nota de Venta al Contado', 'letra' => 'A', 'desc' => 'NOTAS DE VENTA AL CONTADO A'],
    6 => ['tipo' => 'Factura', 'letra' => 'B', 'desc' => 'FACTURA B'],
    7 => ['tipo' => 'Nota de Débito', 'letra' => 'B', 'desc' => 'NOTA DE DEBITO B'],
    8 => ['tipo' => 'Nota de Crédito', 'letra' => 'B', 'desc' => 'NOTA DE CREDITO B'],
    9 => ['tipo' => 'Recibo', 'letra' => 'B', 'desc' => 'RECIBO B'],
    10 => ['tipo' => 'Nota de Venta al Contado', 'letra' => 'B', 'desc' => 'NOTAS DE VENTA AL CONTADO B'],
    11 => ['tipo' => 'Factura', 'letra' => 'C', 'desc' => 'FACTURA C'],
    12 => ['tipo' => 'Nota de Débito', 'letra' => 'C', 'desc' => 'NOTA DE DEBITO C'],
    13 => ['tipo' => 'Nota de Crédito', 'letra' => 'C', 'desc' => 'NOTA DE CREDITO C'],
    15 => ['tipo' => 'Recibo', 'letra' => 'C', 'desc' => 'RECIBO C'],
    16 => ['tipo' => 'Nota de Venta al Contado', 'letra' => 'C', 'desc' => 'NOTAS DE VENTA AL CONTADO C'],
    17 => ['tipo' => 'Liquidación', 'letra' => 'A', 'desc' => 'LIQUIDACION DE SERVICIOS PUBLICOS CLASE A'],
    18 => ['tipo' => 'Liquidación', 'letra' => 'B', 'desc' => 'LIQUIDACION DE SERVICIOS PUBLICOS CLASE B'],
    19 => ['tipo' => 'Factura', 'letra' => '', 'desc' => 'FACTURA POR OPERACIONES CON EL EXTERIOR'],
    20 => ['tipo' => 'Nota de Débito', 'letra' => '', 'desc' => 'NOTA DE DEBITO POR OPERACIONES CON EL EXTERIOR'],
    21 => ['tipo' => 'Nota de Crédito', 'letra' => '', 'desc' => 'NOTA DE CREDITO POR OPERACIONES CON EL EXTERIOR'],
    22 => ['tipo' => 'Factura', 'letra' => '', 'desc' => 'FACTURA PERMISO EXPORTACION SIMPLIFICADO - DTO. 855/97'],
    23 => ['tipo' => 'Comprobante', 'letra' => 'A', 'desc' => 'COMPROBANTES CLASE "A" DE COMPRA PRIMARIA PARA EL SECTOR PESQUERO MARITIMO'],
    24 => ['tipo' => 'Comprobante', 'letra' => 'A', 'desc' => 'COMPROBANTES CLASE "A" DE CONSIGNACION PRIMARIA PARA EL SECTOR PESQUERO MARITIMO'],
    25 => ['tipo' => 'Comprobante', 'letra' => 'B', 'desc' => 'COMPROBANTES CLASE "B" DE COMPRA PRIMARIA PARA EL SECTOR PESQUERO MARITIMO'],
    26 => ['tipo' => 'Comprobante', 'letra' => 'B', 'desc' => 'COMPROBANTES CLASE "B" DE CONSIGNACION PRIMARIA PARA EL SECTOR PESQUERO MARITIMO'],
    27 => ['tipo' => 'Liquidación', 'letra' => 'A', 'desc' => 'LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE A'],
    28 => ['tipo' => 'Liquidación', 'letra' => 'B', 'desc' => 'LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE B'],
    29 => ['tipo' => 'Liquidación', 'letra' => 'C', 'desc' => 'LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE C'],
    30 => ['tipo' => 'Comprobante', 'letra' => '', 'desc' => 'COMPROBANTE DE COMPRA DE BIENES USADOS'],
    31 => ['tipo' => 'Mandato/Consignación', 'letra' => '', 'desc' => 'MANDATO - CONSIGNACION'],
    32 => ['tipo' => 'Comprobante', 'letra' => 'A', 'desc' => 'COMPROBANTE DE COMPRA DE MATERIALES A RECICLAR PROVENIENTE DE RESIDUOS'],
    33 => ['tipo' => 'Liquidación', 'letra' => '', 'desc' => 'LIQUIDACION PRIMARIA DE GRANOS'],
    34 => ['tipo' => 'Comprobante', 'letra' => 'A', 'desc' => 'COMPROBANTES A DEL ANEXO I, APARTADO A,  INCISO F)  R.G. N°  1415'],
    35 => ['tipo' => 'Comprobante', 'letra' => 'A', 'desc' => 'COMPROBANTES B  DEL ANEXO I, APARTADO A, INC. F), R.G. N° 1415'],
    36 => ['tipo' => 'Comprobante', 'letra' => 'A', 'desc' => 'COMPROBANTES C DEL ANEXO I, APARTADO A, INC.F), R.G. N° 1415'],
    37 => ['tipo' => 'Notas De Debito O Documentos Equivalentes Que Cumplan Con La R.G. N° 1415', 'letra' => '', 'desc' => 'NOTAS DE DEBITO O DOCUMENTOS EQUIVALENTES QUE CUMPLAN CON LA R.G. N° 1415'],
    38 => ['tipo' => 'Notas De Credito O Documentos Equivalentes Que Cumplan Con La R.G. N° 1415', 'letra' => '', 'desc' => 'NOTAS DE CREDITO O DOCUMENTOS EQUIVALENTES QUE CUMPLAN CON LA R.G. N° 1415'],
    39 => ['tipo' => 'Otros Comprobantes', 'letra' => 'A', 'desc' => 'OTROS COMPROBANTES A QUE CUMPLEN CON LA R G  N° 1415'],
    40 => ['tipo' => 'Otros Comprobantes', 'letra' => 'B', 'desc' => 'OTROS COMPROBANTES B QUE CUMPLAN CON LA R.G. N° 1415'],
    41 => ['tipo' => 'Otros Comprobantes', 'letra' => 'C', 'desc' => 'OTROS COMPROBANTES C QUE CUMPLAN CON LA R.G. N° 1415'],
    43 => ['tipo' => 'Nota de Crédito', 'letra' => 'B', 'desc' => 'NOTA DE CREDITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE B'],
    44 => ['tipo' => 'Nota de Crédito', 'letra' => 'C', 'desc' => 'NOTA DE CREDITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE C'],
    45 => ['tipo' => 'Nota de Débito', 'letra' => 'A', 'desc' => 'NOTA DE DEBITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE A'],
    46 => ['tipo' => 'Nota de Débito', 'letra' => 'B', 'desc' => 'NOTA DE DEBITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE B'],
    47 => ['tipo' => 'Nota de Débito', 'letra' => 'C', 'desc' => 'NOTA DE DEBITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE C'],
    48 => ['tipo' => 'Nota de Crédito', 'letra' => 'A', 'desc' => 'NOTA DE CREDITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE A'],
    49 => ['tipo' => 'Comprobante', 'letra' => 'A', 'desc' => 'COMPROBANTES DE COMPRA DE BIENES USADOS NO REGISTRABLES A CONSUMIDORES FINALES'],
    51 => ['tipo' => 'Factura', 'letra' => 'A', 'desc' => 'FACTURA A CON LEYENDA "OPERACIÓN SUJETA A RETENCIÓN"'],
    52 => ['tipo' => 'Nota de Débito', 'letra' => 'A', 'desc' => 'NOTA DE DEBITO A CON LEYENDA "OPERACIÓN SUJETA A RETENCIÓN"'],
    53 => ['tipo' => 'Nota de Crédito', 'letra' => 'A', 'desc' => 'NOTA DE CREDITO A CON LEYENDA "OPERACIÓN SUJETA A RETENCIÓN"'],
    54 => ['tipo' => 'Recibo', 'letra' => 'A', 'desc' => 'RECIBO A CON LEYENDA "OPERACIÓN SUJETA A RETENCIÓN"'],
    55 => ['tipo' => 'Nota de Venta al Contado', 'letra' => 'A', 'desc' => 'NOTAS DE VENTA AL CONTADO A CON LEYENDA "OPERACIÓN SUJETA A RETENCIÓN"'],
    56 => ['tipo' => 'Comprobante', 'letra' => 'A', 'desc' => 'COMPROBANTES A CON LEYENDA "OPERACIÓN SUJETA A RETENCIÓN" DEL ANEXO I, APARTADO A, INC. F), R.G. N° 1.415'],
    57 => ['tipo' => 'Otros Comprobantes', 'letra' => 'A', 'desc' => 'OTROS COMPROBANTES A CON LEYENDA "OPERACIÓN SUJETA A RETENCIÓN"QUE CUMPLAN CON LA R.G. N° 1.415'],
    58 => ['tipo' => 'Cuenta de Venta y Líquido Producto', 'letra' => 'A', 'desc' => 'CUENTA DE VENTA Y LIQUIDO PRODUCTO A CON LEYENDA "OPERACIÓN SUJETA A RETENCIÓN"'],
    59 => ['tipo' => 'Liquidación', 'letra' => 'A', 'desc' => 'LIQUIDACION A CON LEYENDA "OPERACIÓN SUJETA A RETENCIÓN"'],
    60 => ['tipo' => 'Cuenta de Venta y Líquido Producto', 'letra' => 'A', 'desc' => 'CUENTAS DE VENTA Y LIQUIDO PRODUCTO A'],
    61 => ['tipo' => 'Cuenta de Venta y Líquido Producto', 'letra' => 'B', 'desc' => 'CUENTAS DE VENTA Y LIQUIDO PRODUCTO B'],
    63 => ['tipo' => 'Liquidación', 'letra' => 'A', 'desc' => 'LIQUIDACIONES A'],
    64 => ['tipo' => 'Liquidación', 'letra' => 'B', 'desc' => 'LIQUIDACIONES B'],
    66 => ['tipo' => 'Despacho de Importación', 'letra' => '', 'desc' => 'DESPACHO DE IMPORTACION'],
    80 => ['tipo' => 'Informe Z', 'letra' => '', 'desc' => 'INFORME DIARIO DE CIERRE (ZETA) - CONTROLADORES FISCALES (*)'],
    81 => ['tipo' => 'Factura', 'letra' => 'A', 'desc' => 'TIQUE FACTURA A (*)'],
    82 => ['tipo' => 'Factura', 'letra' => 'B', 'desc' => 'TIQUE FACTURA B (*)'],
    83 => ['tipo' => 'Tique', 'letra' => '', 'desc' => 'TIQUE (*)'],
    88 => ['tipo' => 'Remito', 'letra' => '', 'desc' => 'REMITO ELECTRONICO'],
    89 => ['tipo' => 'Resumen de Datos', 'letra' => '', 'desc' => 'RESUMEN DE DATOS'],
    90 => ['tipo' => 'Otros Comprobantes', 'letra' => '', 'desc' => 'OTROS COMPROBANTES - DOCUMENTOS EXCEPTUADOS - NOTAS DE CREDITO'],
    91 => ['tipo' => 'Remito', 'letra' => '', 'desc' => 'REMITOS R'],
    99 => ['tipo' => 'Otros Comprobantes', 'letra' => '', 'desc' => 'OTROS COMPROBANTES QUE NO CUMPLEN O ESTÁN EXCEPTUADOS DE LA R.G. 1415 Y SUS MODIF'],
    109 => ['tipo' => 'Tique', 'letra' => 'C', 'desc' => 'TIQUE C'],
    993 => ['tipo' => 'Remito', 'letra' => '', 'desc' => 'REMITO ELECTRÓNICO HARINERO - AUTOMOTOR'],
    994 => ['tipo' => 'Remito', 'letra' => '', 'desc' => 'REMITO ELECTRÓNICO HARINERO - FERROVIARIO'],
    995 => ['tipo' => 'Remito', 'letra' => '', 'desc' => 'REMITO ELECTRÓNICO CÁRNICO'],
    997 => ['tipo' => 'Remito', 'letra' => '', 'desc' => 'Remito Electrónico para Azúcar, Alcohol y Subproductos -Mercado Interno-'],
    998 => ['tipo' => 'Remito', 'letra' => '', 'desc' => 'Remito Electrónico para Azúcar, Alcohol y Subproductos -Exportación-'],
];